#cloud-config
hostname: ubuntu

users:
  - name: ubuntu
    plain_text_passwd: ubuntu
    lock_passwd: false
    primary_group: ubuntu
    groups: sudo, wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_import_id: None
